version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./temp:/app/temp
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=your-secret-key
      - UPLOAD_FOLDER=/app/uploads
      - TEMP_FOLDER=/app/temp
    restart: unless-stopped
    
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./uploads:/var/www/uploads:ro
    depends_on:
      - web
    restart: unless-stopped
