services:
  - type: web
    name: watchtogether
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    plan: free
    envVars:
      - key: SECRET_KEY
        value: dev-secret-key
